name: 03 - Workflow Runners
on:
    push:
    workflow_dispatch:
jobs:
    ubuntu-echo:
        runs-on: ubuntu-latest
        steps:
            - name: Show OS
              run: |
                echo "I'm running on ${{ runner.os }}"
    windows-echo:
        runs-on: windows-latest
        steps:
            - name: Show OS
              run: |
                echo "I'm running on ${{ runner.os }}" 
    mac-echo:
        runs-on: macos-latest
        steps:
            - name: Show OS
              run: |
                echo "I'm running on ${{ runner.os }}"                         

