name: 04 - Using Actions
on: push
jobs:
    build:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: 04-using-actions/reach-app
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
            - name: Printing folders
              run: ls -la 
            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                node-version: '20.x'
            - name: Install Dependencies
              run: npm ci
            #   working-directory: 04-using-actions/reach-app
            - name: Run Unit Tests
              run: npm test
            #   working-directory: 04-using-actions/reach-app

        #Checkout the code from the repository
        #Install deps of our reach application
        #Execute Automated Tests

